if(NOT EXISTS "${PROJECT_SOURCE_DIR}/lib/cute/cute/cute.h")
  message(STATUS "CUTE: Submodule 'lib/cute' not checked out. Disabling tests.")
  set(CUTE_FOUND OFF)
else()
  message(STATUS "CUTE: Found submodule 'lib/cute'. Enabling tests.")
  include("CTest")
  enable_testing()
  add_library("LIB::CUTE" INTERFACE IMPORTED)
  set_property(TARGET "LIB::CUTE" PROPERTY INTERFACE_INCLUDE_DIRECTORIES "${PROJECT_SOURCE_DIR}/lib/cute")
  set(CUTE_FOUND ON)
endif()